import { isPlatformBrowser } from '@angular/common';
import { ChangeDetectorRef,Component,Inject,OnInit,PLATFORM_ID } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { finalize, timeout } from 'rxjs';
import { ApiService,StashAccountRow,StashFarmAccount,StorageSnapshot } from '../../services/api';
type FarmStatus='Active'|'Farmed'|'Banned'; type StorageStatus='Not Banned'|'Banned';
interface FarmAccount{profileId:number;login:string;vm:string;status:FarmStatus;balance:string;}
interface StorageAccount{profileId:number;login:string;email:string;status:StorageStatus;linkedFarmAccounts:string[];storedItems:number;lastActivity:string;hasSteamGuard:boolean;}
@Component({selector:'app-storage',imports:[FormsModule],templateUrl:'./storage.html',styleUrls:['./storage.css','./storage-table.css']})
export class Storage implements OnInit{
 farmAccounts:FarmAccount[]=[];storageAccounts:StorageAccount[]=[];private farmByLogin=new Map<string,FarmAccount>();private linkedOwnerByLogin=new Map<string,number>();selectedStorage:StorageAccount|null=null;pendingDeleteStorage:StorageAccount|null=null;
 addStorageOpen=false;steamGuardModalOpen=false;loadingFarmAccounts=false;saving=false;newStorageLogin='';newStorageEmail='';newStoragePassword='';newStorageStatus:StorageStatus='Not Banned';newStorageFarmAccounts=new Set<string>();addStorageError='';accountSearch='';manageAccountSearch='';manageFarmAccounts=new Set<string>();manageStorageStatus:StorageStatus='Not Banned';selectedSteamGuardStorage:StorageAccount|null=null;selectedSteamGuardFile:File|null=null;steamGuardTradeToken='';notification='';
 constructor(private api:ApiService,private cdr:ChangeDetectorRef,@Inject(PLATFORM_ID) private platformId:object){}
 ngOnInit(){if(!isPlatformBrowser(this.platformId))return;this.loadStorageSnapshot();}
 get storageCount(){return this.storageAccounts.length} get activeStorageCount(){return this.storageAccounts.filter(x=>x.status==='Not Banned').length} get bannedCount(){return this.storageAccounts.filter(x=>x.status==='Banned').length} get linkedFarmCount(){return this.storageAccounts.reduce((n,x)=>n+x.linkedFarmAccounts.length,0)} get unlinkedFarmCount(){return this.farmAccounts.length-this.linkedOwnerByLogin.size}
 get assignableFarmAccounts(){const q=this.accountSearch.trim().toLowerCase();return this.farmAccounts.filter(x=>!this.linkedOwnerByLogin.has(x.login)&&(!q||x.login.toLowerCase().includes(q)||x.vm.toLowerCase().includes(q)))}
 get manageableFarmAccounts(){if(!this.selectedStorage)return[];const q=this.manageAccountSearch.trim().toLowerCase();return this.farmAccounts.filter(x=>{const owner=this.linkedOwnerByLogin.get(x.login);const other=owner!==undefined&&owner!==this.selectedStorage?.profileId;return !other&&(x.status!=='Banned'||this.manageFarmAccounts.has(x.login))&&(!q||x.login.toLowerCase().includes(q)||x.vm.toLowerCase().includes(q))})}
 get addedManageFarmAccounts(){return this.manageableFarmAccounts.filter(x=>this.manageFarmAccounts.has(x.login))} get notAddedManageFarmAccounts(){return this.manageableFarmAccounts.filter(x=>!this.manageFarmAccounts.has(x.login))}
 farmAccount(login:string){return this.farmByLogin.get(login)} isFarmLinked(login:string){return this.linkedOwnerByLogin.has(login)}
 openAddStorage(){this.newStorageLogin='';this.newStorageEmail='';this.newStoragePassword='';this.newStorageStatus='Not Banned';this.newStorageFarmAccounts=new Set();this.accountSearch='';this.addStorageError='';this.addStorageOpen=true} closeAddStorage(){this.addStorageOpen=false;this.addStorageError=''} isNewFarmSelected(login:string){return this.newStorageFarmAccounts.has(login)}
 toggleNewFarmAccount(a:FarmAccount){if(a.status==='Banned'||this.isFarmLinked(a.login))return;const s=new Set(this.newStorageFarmAccounts);s.has(a.login)?s.delete(a.login):s.add(a.login);this.newStorageFarmAccounts=s}
 createStorage(){const login=this.newStorageLogin.trim(),email=this.newStorageEmail.trim();if(!login||!email||!this.newStoragePassword){this.addStorageError='Login, email and password are required.';return}if(!/^\S+@\S+\.\S+$/.test(email)){this.addStorageError='Enter a valid email.';return}const farmLogins=[...this.newStorageFarmAccounts];const request={login,email,password:this.newStoragePassword,blocked:this.newStorageStatus==='Banned',farmProfileIds:this.ids(this.newStorageFarmAccounts)};const temporaryId=-Date.now();const optimistic:StorageAccount={profileId:temporaryId,login,email,status:this.newStorageStatus,linkedFarmAccounts:farmLogins,storedItems:0,lastActivity:'Saving...',hasSteamGuard:false};this.storageAccounts=[...this.storageAccounts,optimistic].sort((a,b)=>a.login.localeCompare(b.login));this.rebuildCaches();this.closeAddStorage();this.saving=true;this.notify('STASH shown; saving in background...');this.api.createStash(request).pipe(timeout(15000),finalize(()=>{this.saving=false;this.cdr.detectChanges()})).subscribe({next:created=>{this.storageAccounts=this.storageAccounts.map(x=>x.profileId===temporaryId?this.mapStash(created):x);this.rebuildCaches();this.notify(login+' stash profile created')},error:e=>{this.storageAccounts=this.storageAccounts.filter(x=>x.profileId!==temporaryId);this.rebuildCaches();this.addStorageOpen=true;this.addStorageError=e?.name==='TimeoutError'?'Server took too long to save. Try again.':this.error(e,'Could not create stash')}})}
 openStorage(s:StorageAccount){this.manageAccountSearch='';this.manageFarmAccounts=new Set(s.linkedFarmAccounts);this.manageStorageStatus=s.status;this.selectedStorage=s} closeStorage(){this.selectedStorage=null;this.manageFarmAccounts=new Set()} isManageFarmSelected(l:string){return this.manageFarmAccounts.has(l)} toggleManageFarmAccount(a:FarmAccount){const s=new Set(this.manageFarmAccounts);s.has(a.login)?s.delete(a.login):s.add(a.login);this.manageFarmAccounts=s}
 saveManagedAccounts(){if(!this.selectedStorage)return;const current=this.selectedStorage;const previous={status:current.status,linkedFarmAccounts:[...current.linkedFarmAccounts],lastActivity:current.lastActivity};const selected=[...this.manageFarmAccounts];const request={email:current.email,blocked:this.manageStorageStatus==='Banned',farmProfileIds:this.ids(this.manageFarmAccounts)};current.status=this.manageStorageStatus;current.linkedFarmAccounts=selected;current.lastActivity='Saving...';this.storageAccounts=this.storageAccounts.map(x=>x.profileId===current.profileId?{...current}:x);this.rebuildCaches();this.closeStorage();this.notify('Changes shown; saving to server...');this.api.updateStash(current.profileId,request).subscribe({next:updated=>{this.storageAccounts=this.storageAccounts.map(x=>x.profileId===updated.profileId?this.mapStash(updated):x);this.rebuildCaches();this.notify('Stash links saved')},error:e=>{this.storageAccounts=this.storageAccounts.map(x=>x.profileId===current.profileId?{...x,...previous}:x);this.rebuildCaches();this.notify(this.error(e,'Could not update stash; changes reverted'))}})}
 openSteamGuardStorage(s:StorageAccount){this.selectedSteamGuardStorage=s;this.selectedSteamGuardFile=null;this.steamGuardTradeToken='';this.steamGuardModalOpen=true}
 closeSteamGuardStorage(){this.steamGuardModalOpen=false;this.selectedSteamGuardStorage=null;this.selectedSteamGuardFile=null}
 selectSteamGuardFile(event:Event){const input=event.target as HTMLInputElement;this.selectedSteamGuardFile=input.files?.[0]??null}
 uploadStashSteamGuard(){if(!this.selectedSteamGuardStorage){return}const token=this.steamGuardTradeToken.trim();if(!this.selectedSteamGuardFile&&!token){this.notify('Choose a .maFile or enter a trade token');return}const login=this.selectedSteamGuardStorage.login;const hasFile=!!this.selectedSteamGuardFile;const request=this.selectedSteamGuardFile?this.api.importSteamGuard(login,this.selectedSteamGuardFile,token):this.api.saveSteamTradeToken(login,token);this.saving=true;request.pipe(timeout(15000),finalize(()=>{this.saving=false;this.cdr.detectChanges()})).subscribe({next:()=>{this.closeSteamGuardStorage();this.loadStashes();this.notify(hasFile?`Steam Guard added to ${login}`:`Trade token saved for ${login}`)},error:e=>{this.notify(e?.name==='TimeoutError'?'Saving timed out':this.error(e,'Could not save Steam Guard or trade token'))}})} askDeleteStorage(s:StorageAccount){this.pendingDeleteStorage=s} cancelDeleteStorage(){this.pendingDeleteStorage=null} confirmDeleteStorage(){if(!this.pendingDeleteStorage)return;const stash=this.pendingDeleteStorage;const previousIndex=this.storageAccounts.findIndex(x=>x.profileId===stash.profileId);this.pendingDeleteStorage=null;this.selectedStorage=null;this.storageAccounts=this.storageAccounts.filter(x=>x.profileId!==stash.profileId);this.rebuildCaches();this.notify('STASH removed; deleting in background...');this.api.deleteStash(stash.profileId).subscribe({next:r=>{this.notify(stash.login+' deleted; '+r.released+' accounts released')},error:e=>{const restored=[...this.storageAccounts];restored.splice(Math.max(0,previousIndex),0,stash);this.storageAccounts=restored;this.rebuildCaches();this.notify(this.error(e,'Could not delete stash; restored'))}})}
 private ids(logins:Set<string>){return [...logins].map(l=>this.farmAccount(l)?.profileId).filter((x):x is number=>x!==undefined)}
 private loadStorageSnapshot(){this.loadingFarmAccounts=true;this.api.storageSnapshot().subscribe({next:snapshot=>{this.applySnapshot(snapshot);this.loadingFarmAccounts=false;this.cdr.detectChanges()},error:e=>{this.loadingFarmAccounts=false;this.notify(this.error(e,'Could not load storage'))}})}
 private loadStashes(){this.api.stashes().subscribe({next:rows=>{this.storageAccounts=rows.map(x=>this.mapStash(x));this.rebuildCaches();this.cdr.detectChanges()},error:e=>this.notify(this.error(e,'Could not load stashes'))})}
 private applySnapshot(snapshot:StorageSnapshot){this.storageAccounts=snapshot.stashes.map(x=>this.mapStash(x));this.farmAccounts=snapshot.farmAccounts.map(x=>this.mapFarm(x));this.rebuildCaches()}
 private mapFarm(x:StashFarmAccount):FarmAccount{return{profileId:x.profileId,login:x.login,vm:x.vmName||'No VM',status:x.blocked?'Banned':x.farmed?'Farmed':'Active',balance:'0.00 EUR'}}
 private rebuildCaches(){this.farmByLogin=new Map(this.farmAccounts.map(x=>[x.login,x]));this.linkedOwnerByLogin=new Map();for(const storage of this.storageAccounts)for(const login of storage.linkedFarmAccounts)this.linkedOwnerByLogin.set(login,storage.profileId)}
 private mapStash(x:StashAccountRow):StorageAccount{return{profileId:x.profileId,login:x.login,email:x.email,status:x.blocked?'Banned':'Not Banned',linkedFarmAccounts:x.linkedAccounts.map(a=>a.login),storedItems:0,lastActivity:'Server',hasSteamGuard:x.hasSteamGuard}}
 private error(e:{error?:unknown},fallback:string){if(typeof e?.error==='string'&&e.error.trim())return e.error;const body=e?.error as {message?:string;detail?:string;error?:string}|undefined;return body?.message||body?.detail||body?.error||fallback} private notify(m:string){this.notification=m;window.setTimeout(()=>{if(this.notification===m)this.notification=''},2600)}
}